name: Convert CSV to JSON

on:
  push:
    paths:
      - 'data/Cerrados Tickets - 20240725.csv'
  workflow_dispatch:

jobs:
  convert-csv-to-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run conversion script
      run: python convert_csv_to_json.py

    - name: Pull latest changes
      run: |
        git pull origin main --rebase
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add data/tickets_data.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update tickets_data.json" && git push)
